# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Change Jar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Change Jar
  pod 'lottie-ios'
  pod 'Alamofire','~> 4.7.0'

  target 'Change JarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Change JarUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
